### ISSUE TITLE
Error: The auto scaling configuration ARN you specified isn't valid. ARN: ''

### ISSUE THREAD

**Issue by hossameldeen** [awslabs/amazon-app-runner-deploy#36]
## Summary

I have a pipeline that was working fine until yesterday. Without making any changes, it started failing today with this error:

```
Error: The auto scaling configuration ARN you specified isn't valid. ARN: ''
```

## Relevant

I highly suspect #33 and [this change](https://github.com/awslabs/amazon-app-runner-deploy/blob/17a435dee343fd6395a23c710ad4edebcf568a5c/CHANGELOG.md?plain=1#L12) are relevant.

https://github.com/awslabs/amazon-app-runner-deploy/blob/17a435dee343fd6395a23c710ad4edebcf568a5c/CHANGELOG.md?plain=1#L12

## Reproduction

**Step configuration that fails:**

```yaml
      - name: Deploy to App Runner Image
        id: deploy-apprunner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: my-app-staging-app-runner-service
          image: ${{ steps.login-ecr.outputs.registry }}/my-app-staging-dotnet-backend:${{ github.sha }}
          access-role-arn: ${{ secrets.ROLE_ARN }}
          region: eu-west-1
          cpu: 1
          memory: 2
          wait-for-service-stability: true
```

**Error screenshot:**

![image](https://user-images.githubusercontent.com/6719916/228446454-c025a66f-9735-4926-afe9-d2131d7adc5e.png)

## [Contributing Guidelines checklist](https://github.com/awslabs/amazon-app-runner-deploy/blob/main/CONTRIBUTING.md#reporting-bugsfeature-requests):

- A reproducible test case or series of steps -> Done, to some extent.
- The version of our code being used -> `awslabs/amazon-app-runner-deploy@main`
- Any modifications you've made relevant to the bug -> Nope. But there are [2.20 changes](https://github.com/awslabs/amazon-app-runner-deploy/blob/main/CHANGELOG.md#220---2023-03-28) that might be relevant.
- Anything unusual about your environment or deployment -> Nope.

## Update: A workaround

You can lock the version of `awslabs/amazon-app-runner-deploy` to `54d9f229e41b80f7cace6480c45ab6dcb1d1af0f`, a version that seems to work.

In your yaml, change:

```
uses: awslabs/amazon-app-runner-deploy@main
```

to:

```
uses: awslabs/amazon-app-runner-deploy@54d9f229e41b80f7cace6480c45ab6dcb1d1af0f
```

It may be a good idea to lock the version even regardless of this issue.
